-- TODO
CREATE DATABASE {{ POSTGRES_GRAFANA_DB }};
CREATE USER {{ POSTGRES_GRAFANA_USER }} WITH PASSWORD '{{ POSTGRES_GRAFANA_PASSWORD }}';
GRANT ALL PRIVILEGES ON DATABASE {{ POSTGRES_GRAFANA_DB }} TO {{ POSTGRES_GRAFANA_USER }};
\connect {{ POSTGRES_GRAFANA_DB }} {{ POSTGRES_ADMIN_USER }};
GRANT ALL ON SCHEMA {{ POSTGRES_GRAFANA_SCHEMA }} TO {{ POSTGRES_GRAFANA_USER }};






