-- TODO
CREATE DATABASE {{ POSTGRES_KEYCLOAK_DB }};
CREATE USER {{ POSTGRES_KEYCLOAK_USER }} WITH PASSWORD '{{ POSTGRES_KEYCLOAK_PASSWORD }}';
GRANT ALL PRIVILEGES ON DATABASE {{ POSTGRES_KEYCLOAK_DB }} TO {{ POSTGRES_KEYCLOAK_USER }};
\connect {{ POSTGRES_KEYCLOAK_DB }} {{ POSTGRES_ADMIN_USER }};
GRANT ALL ON SCHEMA {{ POSTGRES_KEYCLOAK_SCHEMA }} TO {{ POSTGRES_KEYCLOAK_USER }};






