{
 "title": "Fluent-bit Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "CPU cores usage over time for each node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by (node_hostname, cpu) (\r\n  100 * (1 - rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current CPU usage for each node",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (node_hostname) (\r\n  100 * (1 - rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM usage over time for each node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg by (node_hostname, cpu) (\r\n100*(1 - (node_memory_MemAvailable_bytes) /(node_memory_MemTotal_bytes))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM usage for each node",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (avg by (node_hostname) (node_memory_MemAvailable_bytes) / avg by (node_hostname) (node_memory_MemTotal_bytes)))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free disk over time for each node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "(sum by (node_hostname)(node_filesystem_avail_bytes / (1024^3)) /  sum by (node_hostname)(node_filesystem_size_bytes / (1024^3))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free disk for each node",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (node_hostname)(node_filesystem_avail_bytes / (1024^3)) /  sum by (node_hostname)(node_filesystem_size_bytes / (1024^3))) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}