{
 "title": "Traefik Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Number of requests to services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (service) (\r\n    traefik_service_requests_total\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Websecure Entrypoint: status code counting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (code) (\r\n  traefik_entrypoint_requests_total{protocol=\"http\", entrypoint=\"websecure\"}\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{service_name=\"vcc_traefik\"}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum) / sum(traefik_entrypoint_requests_total) * 1000",
     "legendFormat": "Average response time (ms)"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_request_duration_seconds_sum) / sum(traefik_entrypoint_requests_total) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traefik Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "{service_name=\"vcc_traefik\"}"
    }
   ]
  }
 ]
}